# database configs
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/qz_store?useTimezone=true&serverTimezone=America/Sao_Paulo
    username: root
    password:
    tomcat:
      test-while-idle: true
      validation-query: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
# jwt
jwt:
  secret: ${JWT_SECRET:rm'!@N=Ke!~p8VTA2ZRK~nMDQX5Uvm!m'D& ]{ @Vr?G;2?XhbC:Qa#9#eMLN\ }x3?JR3.2zr~v)gYF^8\:8>:XfB:Ww75N/emt9Yj[bQMNCWwW\J?N,nvH.<2\.r~w]*e~vgak)X"v8H`MH/7"2E`,^k@n<vE-wD3g9JWPy;CrY*.Kd2_D])=><D?YhBaSua5hW%{2]_FVXzb9`8FH^b[X3jzVER&:jw2<=c38=>L/zBq`}C6tT*cCSVC^c]-L}&/}
  expiration: 86400000

integrations:
  paypal:
    sandbox-base-url: https://api-m.sandbox.paypal.com
    client-id: AczeFRWyiLiXvWvUL6rhlAoN7N0T-nbbredt0RjbDwQKJ2EOOIVonsDrZ7w2O07lagtUsX9vKDejQQw7
    secret-id: EOP09ivQXspfrT9BNpWaeQvaLR2drVEPk6jETz2DgziNE2kfTdR5JgfNp1jlI3WwbiwRANPOAqbOG9Po
  shipping:
    url: https://sp.freterapido.com
  viaCep:
    url: https://viacep.com.br/ws

server:
  error:
    include-stacktrace: never